a = int(input())
b = int(input())
hundred = int(b/100)
ten = int((b - hundred*100)/10)
one = (b - (hundred*100 + ten*10))

print(a*one)
print(a*ten)
print(a*hundred)
print(a*one + a*ten*10 + a*hundred*100)